- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest  # Ensure pytest is installed

- name: Run tests
  run: pytest
